// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zcqiertprazzxjerhzju.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpjcWllcnRwcmF6enhqZXJoemp1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk3MTk2NTAsImV4cCI6MjA4NTI5NTY1MH0.LjrhEWi91Q46qPKVxGivDUSpToTZLWcfgxcHe3tr1UA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});